### PR TITLE
Change of URLs in Transport.MD so it won't change the locale

### PR DESCRIPTION
**Pull request by easymoney322**
Currently these two hyperlinks in the file are leading to the version of the fallback page on Chinese language, so after clicking on the link users must change the locale again.
I suggest changing the URL in links so users would keep their current locale.

### CODE REVIEW

**Comment by easymoney322** [comment]
It looks like CN language sometimes [doesn't use](https://github.com/XTLS/Xray-docs-next/blob/04748f79c00cd4beed3dd873f0654bb2a5672d54/docs/config/transport.md?plain=1#L368) relative paths either.

Im not very familiar with markdown language, but it looks like that in the master branch, even in the same file 2+ formatings co-exist:
Isn't [this line](https://github.com/XTLS/Xray-docs-next/blob/04748f79c00cd4beed3dd873f0654bb2a5672d54/docs/config/transport.md?plain=1#L414) supposed to be like `[TLSObject](#tlsobject)`?

**Comment by easymoney322** [comment]
I've made requested changes, and it looks like working as intended now.
As for other files, should I make a separate PR?

**Comment by iambabyninja** [comment]
Сейчас я пересмотрел ранние комиты, да, проблема есть не только в этом документе, нужно исправлять так же другие.
Я приведу в выходные в порядок ссылки.

Iam check the earlier commits, and yes, the problem is not only in this document; other documents need fixing as well. I will sort out the links over the weekend.

**Comment by yuhan6665** [comment]
Looks good. Thanks!

**Pull request merged**
