### PR TITLE
Update grpc.md

### PR DESCRIPTION
**Pull request by SQLimit**
35536 ---> 65536

### CODE REVIEW

**Comment by chika0801** [comment]
2333

**Comment by SQLimit** [comment]
> 2333
我就把3改成6，这prettier直接过不去了。。

**Comment by Winston2084** [comment]
> > 2333
> > 我就把3改成6，这prettier直接过不去了。。

There are some other files that do not meet prettier's formatting requirements, it's not your error.

**Comment by SQLimit** [comment]
> > > 2333
> > > 我就把3改成6，这prettier直接过不去了。。
> 
> There are some other files that do not meet prettier's formatting requirements, it's not your error.

Thanks for explaination

**Comment by yuhan6665** [comment]
Thanks!

**Pull request merged**
