### PR TITLE
[CN/EN/RU] Remove legacy `timeout` config

### PR DESCRIPTION
**Pull request by KobeArthurScofield**
以为继续在代码里面删史结果发现 dokodemo-door 和 HTTP 的 `timeout` 配置还挂在那里，还得先弃用一段时间再删，遂先在文档清理之。

移除内容：

- `dokodemo-door` (inbound)：应该退役的 `timeout` 设置项，顺便给英文文档补了示例；
- `http` (inbound)：应该退役的 `timeout` 设置项。

以上移除项以 `userLevel` （应先在 `policy` > `levels` 中先配置好 `connIdle`）替代。代码计划在 v25 开始前移除。

顺手再调整下大史记的排版并处理了一处手滑。

顺便给俄语文档放了个 wireguard inbound，但是得有缘人翻译。

### CODE REVIEW

**Comment by Fangliding** [comment]
这些移除选项都是确认没用的吧

**Comment by KobeArthurScofield** [comment]
是，都能替代
其实所有单独的 timeout 早就已经是标记了弃用，就是删到一半就断了

**Comment by mmmray** [comment]
if there is an intent to deprecate something, i think it's best to use `<detail>` or HTML comment. otherwise somebody might think it's a mistake of the document and re-add it one year later

**Comment by KobeArthurScofield** [comment]
> if there is an intent to deprecate something, i think it's best to use `<detail>` or HTML comment. otherwise somebody might think it's a mistake of the document and re-add it one year later

Thank you, I think we can have it in the normal deprecation procedure ;-)

**Pull request merged**
