### PR TITLE
Several Chinese characters in the English document

### PR DESCRIPTION
**Pull request by caikun233**
It seems English documentation hasn't been updated for a long time?

### CODE REVIEW

**Comment by Fangliding** [comment]
Maybe the machine translator missed it
To be honest, if someone could translate the entire document by hand, I would greatly admire he

**Comment by caikun233** [comment]
> Maybe the machine translator missed it To be honest, if someone could translate the entire document by hand, I would greatly admire he

我这几天熟悉一下Vuepress试试看吧, not small project

**Comment by Fangliding** [comment]
问题倒是不大 机翻有错不过应该还是不多 有的话pr改掉就是了 我只是说明一下用机翻的原因（虽然不是我翻的）
唯一的小问题是我只有精力维护中文文档 不过也倒是有人来sync

**Comment by jindongjie** [comment]
> 问题倒是不大 机翻有错不过应该还是不多 有的话pr改掉就是了 我只是说明一下用机翻的原因（虽然不是我翻的） 唯一的小问题是我只有精力维护中文文档 不过也倒是有人来sync

我可以来试试，我想用chatgpt加手动校准

**Comment by jindongjie** [comment]
> 问题倒是不大 机翻有错不过应该还是不多 有的话pr改掉就是了 我只是说明一下用机翻的原因（虽然不是我翻的） 唯一的小问题是我只有精力维护中文文档 不过也倒是有人来sync

目前哪些章节比较重要啊？我一直使用该项目，想做一些贡献，刚好看到了这个问题

**Comment by mmmray** [comment]
on each english page, there are warnings like this:

image

e.g. https://xtls.github.io/en/config/transport.html

as for "which are most important", think about what documents are important to your own usage. I also just fix issues as I encounter them during usage.

**Comment by mmmray** [comment]
Another good way to help out here is to look at the recent changes to xray-docs-next and see if they need to be ported to other languages.

**Comment by jindongjie** [comment]
> Another good way to help out here is to look at the recent changes to xray-docs-next and see if they need to be ported to other languages.

Thank u~!

**Pull request merged**
